// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Message {
    "id": number | null;
    "threadId": number;
    "originalText": string;
    "text": string;
    "provider": string;
    "durationSecs": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "deletedAt": time$0.Time | null;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = null;
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = 0;
        }
        if (!("originalText" in $$source)) {
            this["originalText"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("durationSecs" in $$source)) {
            this["durationSecs"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("deletedAt" in $$source)) {
            this["deletedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class Thread {
    "id": number | null;
    "name": string;
    "pinned": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "deletedAt": time$0.Time | null;

    /** Creates a new Thread instance. */
    constructor($$source: Partial<Thread> = {}) {
        if (!("id" in $$source)) {
            this["id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("deletedAt" in $$source)) {
            this["deletedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thread instance from a string or object.
     */
    static createFrom($$source: any = {}): Thread {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Thread($$parsedSource as Partial<Thread>);
    }
}
