// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";

export function AreAPIKeysConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(3002748279);
}

/**
 * CancelRecording cancels recording in progress and emits EventRecordingStopped.
 */
export function CancelRecording(): $CancellablePromise<void> {
    return $Call.ByID(1993463310);
}

export function DeleteMessage(id: number): $CancellablePromise<void> {
    return $Call.ByID(4055978473, id);
}

export function DeleteThread(id: number): $CancellablePromise<void> {
    return $Call.ByID(1186337974, id);
}

export function GetAllSettings(): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(1224888095).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetMessages(threadID: number): $CancellablePromise<storage$0.Message[]> {
    return $Call.ByID(3832618599, threadID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(48053349, key);
}

export function GetThreads(): $CancellablePromise<storage$0.Thread[]> {
    return $Call.ByID(972270404).then(($result: any) => {
        return $$createType4($result);
    });
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(542966029);
}

export function OnTrayClick(): $CancellablePromise<void> {
    return $Call.ByID(852014744);
}

export function RenameThread(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(727416435, id, name);
}

/**
 * SelectThread sets the active thread. Setting 0 will clear the current thread
 */
export function SelectThread(id: number): $CancellablePromise<void> {
    return $Call.ByID(2901549873, id);
}

export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4121261467, app);
}

export function SetMenuItems(start: application$0.MenuItem | null, stop: application$0.MenuItem | null, cancel: application$0.MenuItem | null): $CancellablePromise<void> {
    return $Call.ByID(2433934512, start, stop, cancel);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4214292049, key, value);
}

export function SetSystemTray(tray: application$0.SystemTray | null): $CancellablePromise<void> {
    return $Call.ByID(2995039438, tray);
}

export function SetThreadPinned(id: number, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(4204398061, id, pinned);
}

export function SetWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, window);
}

export function ShowSettings(): $CancellablePromise<void> {
    return $Call.ByID(1646582409);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(31117496);
}

/**
 * StartRecording starts recording using the preconfigured recorder.
 */
export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(4179347122);
}

/**
 * StopRecording stops recording, cleans up provider WS and
 * Will use the current activeThreadID to manage creating/appended to thread
 */
export function StopRecording(): $CancellablePromise<void> {
    return $Call.ByID(3372080196);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = storage$0.Message.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = storage$0.Thread.createFrom;
const $$createType4 = $Create.Array($$createType3);
