// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CancelRecording cancels recording in progress and emits EventRecordingStopped.
 */
export function CancelRecording(): $CancellablePromise<void> {
    return $Call.ByID(1993463310);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(542966029);
}

export function IsRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(2249416628);
}

export function OnTrayClick(): $CancellablePromise<void> {
    return $Call.ByID(852014744);
}

export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4121261467, app);
}

export function SetMenuItems(start: application$0.MenuItem | null, stop: application$0.MenuItem | null, cancel: application$0.MenuItem | null): $CancellablePromise<void> {
    return $Call.ByID(2433934512, start, stop, cancel);
}

export function SetSystemTray(tray: application$0.SystemTray | null): $CancellablePromise<void> {
    return $Call.ByID(2995039438, tray);
}

export function SetWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, window);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(31117496);
}

/**
 * StartRecording starts recording using the preconfigured recorder.
 * 
 * Emits "recording:started" once the recording thread starts.
 * 
 * Emits "recording:progress" periodically.
 */
export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(4179347122);
}

/**
 * StopRecording stops recording and triggers transcription asynchronously.
 * 
 * Emits "recording:stopped" before starting transcription.
 * 
 * Emits "transcription:started" before transcription starts.
 * 
 * Emits "transcription:completed" with the transcription result.
 */
export function StopRecording(): $CancellablePromise<void> {
    return $Call.ByID(3372080196);
}
