// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelRecording stops recording without transcribing
 */
export function CancelRecording(): $CancellablePromise<void> {
    return $Call.ByID(1993463310);
}

/**
 * GetRecordingStatus returns current recording state
 */
export function GetRecordingStatus(): $CancellablePromise<$models.RecordingStatus> {
    return $Call.ByID(881621012).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartRecording begins audio capture
 */
export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(4179347122);
}

/**
 * StopRecording stops audio capture and sends to Deepgram for transcription
 */
export function StopRecording(): $CancellablePromise<$models.TranscriptionResult | null> {
    return $Call.ByID(3372080196).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RecordingStatus.createFrom;
const $$createType1 = $models.TranscriptionResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
