// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function AreAPIKeysConfigured() {
    return $Call.ByID(3002748279);
}

/**
 * CancelRecording cancels recording in progress and emits EventRecordingStopped.
 * @returns {$CancellablePromise<void>}
 */
export function CancelRecording() {
    return $Call.ByID(1993463310);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMessage(id) {
    return $Call.ByID(4055978473, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteThread(id) {
    return $Call.ByID(1186337974, id);
}

/**
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAllSettings() {
    return $Call.ByID(1224888095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} threadID
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessages(threadID) {
    return $Call.ByID(3832618599, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(48053349, key);
}

/**
 * @returns {$CancellablePromise<storage$0.Thread[]>}
 */
export function GetThreads() {
    return $Call.ByID(972270404).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(542966029);
}

/**
 * ImproveMessageText improves the original text of a message using OpenAI
 * Returns the improved text immediately if already processed, otherwise processes asynchronously
 * @param {number} messageID
 * @returns {$CancellablePromise<void>}
 */
export function ImproveMessageText(messageID) {
    return $Call.ByID(4050467057, messageID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OnTrayClick() {
    return $Call.ByID(852014744);
}

/**
 * @param {number} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameThread(id, name) {
    return $Call.ByID(727416435, id, name);
}

/**
 * SelectThread sets the active thread. Setting 0 will clear the current thread
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function SelectThread(id) {
    return $Call.ByID(2901549873, id);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(4121261467, app);
}

/**
 * @param {application$0.MenuItem | null} start
 * @param {application$0.MenuItem | null} stop
 * @param {application$0.MenuItem | null} cancel
 * @returns {$CancellablePromise<void>}
 */
export function SetMenuItems(start, stop, cancel) {
    return $Call.ByID(2433934512, start, stop, cancel);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

/**
 * @param {application$0.SystemTray | null} tray
 * @returns {$CancellablePromise<void>}
 */
export function SetSystemTray(tray) {
    return $Call.ByID(2995039438, tray);
}

/**
 * @param {number} id
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetThreadPinned(id, pinned) {
    return $Call.ByID(4204398061, id, pinned);
}

/**
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function SetWindow(window) {
    return $Call.ByID(3654517795, window);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowSettings() {
    return $Call.ByID(1646582409);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(31117496);
}

/**
 * StartRecording starts recording using the preconfigured recorder.
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording() {
    return $Call.ByID(4179347122);
}

/**
 * StopRecording stops recording, cleans up provider WS and
 * Will use the current activeThreadID to manage creating/appended to thread
 * @returns {$CancellablePromise<void>}
 */
export function StopRecording() {
    return $Call.ByID(3372080196);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = storage$0.Message.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = storage$0.Thread.createFrom;
const $$createType4 = $Create.Array($$createType3);
