// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RecordingStatus {
    "is_recording": boolean;
    "duration_secs": number;

    /** Creates a new RecordingStatus instance. */
    constructor($$source: Partial<RecordingStatus> = {}) {
        if (!("is_recording" in $$source)) {
            this["is_recording"] = false;
        }
        if (!("duration_secs" in $$source)) {
            this["duration_secs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingStatus($$parsedSource as Partial<RecordingStatus>);
    }
}

export class TranscriptionResult {
    "text": string;
    "provider": string;

    /** Creates a new TranscriptionResult instance. */
    constructor($$source: Partial<TranscriptionResult> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TranscriptionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptionResult($$parsedSource as Partial<TranscriptionResult>);
    }
}
